mysite/mysite/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("polls/", include("polls.urls")),
    path("admin/", admin.site.urls),
]

mysite/polls/urls.py
from django.urls import path

from . import views

app_name = "polls"

urlpatterns = [
    # ex: /polls/
    path("", views.IndexView.as_view(), name="index"),
    # ex: /polls/about/
    path("about/", views.about, name="about"),
    # ex: /polls/all-questions/
    path("all-questions/", views.AllQuestionsView.as_view(), name="show_all_questions"),
    # ex: /polls/5/
    path("<int:pk>/", views.Detail.as_view(), name="detail"),
    # ex: /polls/5/results/
    path("<int:pk>/results/", views.ResultsView.as_view(), name="results"),
    # ex: /polls/5/vote/
    path("<int:question_id>/vote/", views.vote, name="vote"),
]

mysite/polls/models.py
import datetime
from django.utils import timezone
# Create your models here.
from django.db import models


class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField("date published")

    def __str__(self):
        return self.question_text #The __str__ method is used to provide a textual representation of the Question object.

    def was_published_recently(self):
        return self.pub_date >= timezone.now() - datetime.timedelta(days=1)


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text #The __str__ method is used to provide a textual representation of the Choice object.

mysite/polls/views.py
from django.http import Http404
from django.shortcuts import render

# Create your views here.

from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
from django.db.models import F

from django.views.generic.list import ListView
from django.views.generic.detail import DetailView

from .models import Question, Choice


class IndexView(ListView):
    template_name = "polls/index.html"
    context_object_name = "latest_question_list"

    def get_queryset(self):
        return Question.objects.order_by("-pub_date")[:3]


class AllQuestionsView(ListView):
    template_name = "polls/all-questions.html"
    context_object_name = "all_questions_list"

    def get_queryset(self):
        return Question.objects.order_by("-pub_date")


def about(request):
    return render(request, "polls/about.html")


class Detail(DetailView):
    model = Question
    template_name = "polls/detail.html"
    context_object_name = "question"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['choices'] = self.object.choice_set.all()
        return context


class ResultsView(DetailView):
    model = Question
    template_name = "polls/results.html"
    context_object_name = "question"


def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    choice_list = question.choice_set.all()
    try:
        selected_choice = choice_list.get(pk=request.POST["choice"])
    except (KeyError, Choice.DoesNotExist):
        # Redisplay the question voting form.
        return render(
            request,
            "polls/detail.html",
            {
                "question": question,
                "choices": choice_list,
                "error_message": "You didn't select a choice.",
            },
        )
    else:
        selected_choice.votes = F('votes') + 1
        selected_choice.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return HttpResponseRedirect(reverse("polls:results", args=(question.id,)))

mysite/polls/templates/polls/about.html
{% load static %}
{% include 'polls/header.html' %}

<body>
        <!-- Main Content-->
        <main class="mb-4">
            <div class="container px-4 px-lg-5">
                <div class="row gx-4 gx-lg-5 justify-content-center">
                    <div class="col-md-10 col-lg-8 col-xl-7">
                        <p>This is a simple poll app made with Django framework. Created for educational purposes to explore Django and its features.</p>

                    </div>
                </div>
            </div>
        </main>

{% include "polls/footer.html" %}

mysite/polls/templates/polls/all-questions.html
{% load static %}
{% include 'polls/header.html' %}

<!-- Main Content-->
<div class="container px-4 px-lg-5">
    <div class="row gx-4 gx-lg-5 justify-content-center">
        <div class="col-md-10 col-lg-8 col-xl-7">
            <!-- Post preview-->


            {% if all_questions_list %}
            {% for question in all_questions_list %}
            <div class="post-preview">
                <a href="post.html">
                    <h2 class="post-title"><a href="{% url 'polls:detail' question.id %}">{{ question.question_text }}</a></h2>
                </a>
                <p class="post-meta">
                    Posted by
                    <a href="#!">Admin</a>
                    on {{ question.pub_date }}
                </p>
            </div>
            <!-- Divider-->
            <hr class="my-4" />

            {% endfor %}
            {% else %}
            <h2>No polls are available.</h2>
            {% endif %}



        </div>
    </div>
</div>
{% include "polls/footer.html" %}

mysite/polls/templates/polls/detail.html
{% load static %}
{% include 'polls/header.html' %}

<article class="mb-4">
    <div class="container px-4 px-lg-5">
        <div class="row gx-4 gx-lg-5 justify-content-center">
            <div class="col-md-10 col-lg-8 col-xl-7">

                <form action="{% url 'polls:vote' question.id %}" method="post">
                    {% csrf_token %}
                    <fieldset>
                        <legend><h1>{{ question.question_text }}</h1></legend>

                        {% if error_message %}
                            <p><strong>{{ error_message }}</strong></p>
                        {% endif %}

                        {% for choice in choices %}
                            <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
                            <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br>
                        {% endfor %}

                    </fieldset>
                    <br>
                    <input type="submit" value="Vote" class="btn btn-primary text-uppercase">

                </form>

            </div>
        </div>
    </div>
</article>

{% include "polls/footer.html" %}

mysite/polls/templates/polls/footer.html
{% load static %}

<!-- Footer-->
        <footer class="border-top">
            <div class="container px-4 px-lg-5">
                <div class="row gx-4 gx-lg-5 justify-content-center">
                    <div class="col-md-10 col-lg-8 col-xl-7">
                        <ul class="list-inline text-center">
                            <li class="list-inline-item">
                                <a href="#!">
                                    <span class="fa-stack fa-lg">
                                        <i class="fas fa-circle fa-stack-2x"></i>
                                        <i class="fab fa-twitter fa-stack-1x fa-inverse"></i>
                                    </span>
                                </a>
                            </li>
                            <li class="list-inline-item">
                                <a href="#!">
                                    <span class="fa-stack fa-lg">
                                        <i class="fas fa-circle fa-stack-2x"></i>
                                        <i class="fab fa-facebook-f fa-stack-1x fa-inverse"></i>
                                    </span>
                                </a>
                            </li>
                            <li class="list-inline-item">
                                <a href="#!">
                                    <span class="fa-stack fa-lg">
                                        <i class="fas fa-circle fa-stack-2x"></i>
                                        <i class="fab fa-github fa-stack-1x fa-inverse"></i>
                                    </span>
                                </a>
                            </li>
                        </ul>
                        <div class="small text-center text-muted fst-italic">Copyright &copy; Poll App 2023</div>
                    </div>
                </div>
            </div>
        </footer>
        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <script src="static/polls/js/scripts.js"></script>
    </body>
</html>

mysite/polls/templates/polls/header.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>Django Poll App</title>
        <link rel="icon" type="image/x-icon" href="assets/favicon.ico" />
        <!-- Font Awesome icons (free version)-->
        <script src="https://use.fontawesome.com/releases/v6.3.0/js/all.js" crossorigin="anonymous"></script>
        <!-- Google fonts-->
        <link href="https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic" rel="stylesheet" type="text/css" />
        <link href="https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800" rel="stylesheet" type="text/css" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="{% static 'polls/css/styles.css' %}" rel="stylesheet" />
    </head>
    <body>
        <!-- Navigation-->
        <nav class="navbar navbar-expand-lg navbar-light" id="mainNav">
            <div class="container px-4 px-lg-5">
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                    Menu
                    <i class="fas fa-bars"></i>
                </button>
                <div class="collapse navbar-collapse" id="navbarResponsive">
                    <ul class="navbar-nav ms-auto py-4 py-lg-0">
                        <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="{% url 'polls:index' %}">Home</a></li>
                        <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="{% url 'polls:about' %}">About</a></li>
                        <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="#!">Contact</a></li>
                    </ul>
                </div>
            </div>
        </nav>
        <!-- Page Header-->
        <header class="masthead" style="background-image: url('/static/polls/assets/img/poll-app-logo.jpg')">
            <div class="container position-relative px-4 px-lg-5">
                <div class="row gx-4 gx-lg-5 justify-content-center">
                    <div class="col-md-10 col-lg-8 col-xl-7">
                        <div class="site-heading">
                            <h1>Poll App</h1>
                            <span class="subheading">A simple Django Poll App</span>
                        </div>
                    </div>
                </div>
            </div>
        </header>

mysite/polls/templates/polls/index.html
{% load static %}
{% include 'polls/header.html' %}

<!-- Main Content-->
<div class="container px-4 px-lg-5">
    <div class="row gx-4 gx-lg-5 justify-content-center">
        <div class="col-md-10 col-lg-8 col-xl-7">
            <!-- Post preview-->


            {% if latest_question_list %}
            {% for question in latest_question_list %}
            <div class="post-preview">
                <a href="post.html">
                    <h2 class="post-title"><a href="{% url 'polls:detail' question.id %}">{{ question.question_text }}</a></h2>
                </a>
                <p class="post-meta">
                    Posted by
                    <a href="#!">Admin</a>
                    on {{ question.pub_date }}
                </p>
            </div>
            <!-- Divider-->
            <hr class="my-4" />

            {% endfor %}
            {% else %}
            <h2>No polls are available.</h2>
            {% endif %}


            <!-- Pager-->
            <div class="d-flex justify-content-end mb-4"><a class="btn btn-primary text-uppercase" href="{% url 'polls:show_all_questions' %}">All questions →</a></div>
        </div>
    </div>
</div>

{% include "polls/footer.html" %}

mysite/polls/templates/polls/results.html
{% load static %}
{% include 'polls/header.html' %}

<article class="mb-4">
    <div class="container px-4 px-lg-5">
        <div class="row gx-4 gx-lg-5 justify-content-center">
            <div class="col-md-10 col-lg-8 col-xl-7">

                <h1>{{ question.question_text }}</h1>
                <br>

                    <ul>
                    {% for choice in question.choice_set.all %}
                        <li>{{ choice.choice_text }} - {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
                    {% endfor %}
                    </ul>
                <br>

                <a href="{% url 'polls:detail' question.id %}" class="btn btn-primary text-uppercase">Click to vote again</a>

            </div>
        </div>
    </div>
</article>

{% include "polls/footer.html" %}